export class CustomerShortInfo {
    constructor(
        public id: number,
        public xin: string,
        public nameRu: string,
        public nameEn: string,
        public nameKz: string,
        public address: string,
        public addressKz: string,
        public addressEn: string,
        public republic: string,
        public oblast: string,
        public region: string,
        public city: string,
        public street: string,
        public typeId: number,
        public countryId: number,
        public typeCode: string,
        public isBeneficiary: boolean,
        public phone: string | string[],
        public mobilePhone: string | string[],
        public phoneFax: string | string[],
        public email: string | string[],
        public jurRegNumber: string,
        public govReg: string,
        public powerAttorneyFullNum: string,
        public isNotResident: boolean,
        public isNotMention: boolean,
        public ownerAddresseeAddress: string,
        public apartment: string,
        public beneficiaryTypeId: number,
        public ownerId?: number
    ) { }
}
