//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iserv.Niis.Notifications.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Iserv.Niis.Notifications.Resources.MessageTemplates", typeof(MessageTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zajavleniju na registraciju dogovora prisvoen  № {0}.  Podrobnee v Lichnom kabinete. Shartty tirkeu otinishine № {0} tagajyndaldy. Tolygyrak Zheke kabinette..
        /// </summary>
        internal static string ContractCreateForStatement {
            get {
                return ResourceManager.GetString("ContractCreateForStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status zajavlenija {0} izmenen na «{1}». Podrobnee v Lichnom kabinete. № {0} otinishtin martebesi «{1}» martebesine ozgertildi.  Tolygyrak Zheke kabinette..
        /// </summary>
        internal static string ContractOnlineStatusChanged {
            get {
                return ResourceManager.GetString("ContractOnlineStatusChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Po zajavleniju № {0} napravleno uvedomlenie. Podrobnee v Lichnom kabinete. № {0} otinish bojynsha habarlama zholdandy. Tolygyrak Zheke kabinette..
        /// </summary>
        internal static string ContractSendNotification {
            get {
                return ResourceManager.GetString("ContractSendNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Po zajavleniju № {0} napravlen zapros. Srok predostavlenija otveta do {1}. Podrobnee v Lichnom kabinete. № {0} otinish bojynsha suratu zholdandy. Zhauap beru merzimi {1} zh. dejin Tolygyrak Zheke kabinette..
        /// </summary>
        internal static string ContractStatementExamination {
            get {
                return ResourceManager.GetString("ContractStatementExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zajavke prisvoen № {0}. Podrobnee v Lichnom kabinete. Otinimge № {0} tagajyndaldy. Tolygyrak Zheke kabinette..
        /// </summary>
        internal static string CreateStageForApplication {
            get {
                return ResourceManager.GetString("CreateStageForApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравствуйте!
        ///Это письмо создано автоматически и не требует ответа.
        ///Описание: {0}
        ///Письма направляйте по адресу: kazpatent@kazpatent.kz 
        /// 
        ///С уважением,
        ///РГП «Национальный институт интеллектуальной собственности» МЮ РК 
        /// 
        ///Call-centre. 8 (7172) 66-15-15.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srok oplaty za jekspertizu pozajavke № {0} do {1}. Podrobnee v Lichnom kabinete. № {0} otiniminin saraptamasy ushin tolemnin merzimi {1} zh. dejin. Tolygyrak Zheke kabinette..
        /// </summary>
        internal static string ExpertisePaymentWaitingStage {
            get {
                return ResourceManager.GetString("ExpertisePaymentWaitingStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napravleno pismo. Podrobnee v Lichnom kabinete. Hat zholdandy. Tolygyrak Zheke kabinette..
        /// </summary>
        internal static string IncomingAnswerLetter {
            get {
                return ResourceManager.GetString("IncomingAnswerLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napravlen schet. Podrobnee v Lichnom kabinete. Shot zholdandy. Tolygyrak Zheke kabinette..
        /// </summary>
        internal static string InvoiceForPayment {
            get {
                return ResourceManager.GetString("InvoiceForPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srok podachi vozrazhenija po zajavke № {0} istekaet {1}. Podrobnee v Lichnom kabinete. № {0} otinim bojynsha karsylyk beru merzimi {1} zh. otedi. Tolygyrak Zheke kabinette..
        /// </summary>
        internal static string ObjectionExpirationTerm {
            get {
                return ResourceManager.GetString("ObjectionExpirationTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status zajavki № {0} izmenen na «{1}». Podrobnee v Lichnom kabinete. № {0} otinimnin martebesi «{1}» martebesine ozgertildi. Tolygyrak Zheke kabinette..
        /// </summary>
        internal static string OnlineStatusChanged {
            get {
                return ResourceManager.GetString("OnlineStatusChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srok oplaty za podachu zajavki № {0} do {1}. Podrobnee v Lichnom kabinete. № {0} otinimin beru ushin tolemnin merzimi {1} zh. dejin. Tolygyrak Zheke kabinette..
        /// </summary>
        internal static string PaymentWaitingStage {
            get {
                return ResourceManager.GetString("PaymentWaitingStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srok oplaty za publikaciju svedenij po zajavke № {0} do {1}. Podrobnee v Lichnom kabinete. № {0} otinim bojynsha malimetterdi zharijalau ushin tolemnin merzimi {1} zh. dejin. Tolygyrak Zheke kabinette..
        /// </summary>
        internal static string PreparationForTransferStage {
            get {
                return ResourceManager.GetString("PreparationForTransferStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uvedomljaem o neobhodimosti oplaty za podderzhanie v sile ohrannogo dokumenta № {0}..
        /// </summary>
        internal static string ProtectionDocSupportAboutToExpire {
            get {
                return ResourceManager.GetString("ProtectionDocSupportAboutToExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srok dejstvija patenta s № {0}  istekaet {1}. Podrobnee v Lichnom kabinete. № {0}  patenttin areket etu merzimi {1} zh. otedi. Tolygyrak Zheke kabinette..
        /// </summary>
        internal static string ProtectionDocValidityAboutToExpire {
            get {
                return ResourceManager.GetString("ProtectionDocValidityAboutToExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vosstanovlenie propushhennogo sroka po zajavke № {0} do {1}. Podrobnee v Lichnom kabinete. № {0} otinim bojynsha zhiberip alfan merzimdi kalpyna keltiru {1} zh. dejin. Tolygyrak Zheke kabinette..
        /// </summary>
        internal static string RecoveryStage {
            get {
                return ResourceManager.GetString("RecoveryStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srok predostavlenija otveta po zajavke № {0} istekaet {1}. Podrobnee v Lichnom kabinete. № {0} otinim bojynsha zhauap beru merzimi {1} zh. otedi. Tolygyrak Zheke kabinette..
        /// </summary>
        internal static string RequestExpirationTerm {
            get {
                return ResourceManager.GetString("RequestExpirationTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Po zajavke № {0} napravleno zaklyuchenie. Podrobnee v Lichnom kabinete. № {0}  otinim bojynsha korytyndy zholdandy. Tolygyrak Zheke kabinette..
        /// </summary>
        internal static string RequestSendConclusion {
            get {
                return ResourceManager.GetString("RequestSendConclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Po zajavke № {0} napravleno uvedomlenie. Podrobnee v Lichnom kabinete. № {0}  otinim bojynsha habarlama zholdandy. Tolygyrak Zheke kabinette..
        /// </summary>
        internal static string RequestSendNotification {
            get {
                return ResourceManager.GetString("RequestSendNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Po zajavke № {0} napravleno reshenie. Podrobnee v Lichnom kabinete. № {0} otinim bojynsha sheshim zholdandy. Tolygyrak Zheke kabinette..
        /// </summary>
        internal static string RequestSendSolution {
            get {
                return ResourceManager.GetString("RequestSendSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Po zajavke № {0} napravleno uvedomlenie. Podrobnee v Lichnom kabinete. № {0} otinim bojynsha habarlama zholdandy. Tolygyrak Zheke kabinette..
        /// </summary>
        internal static string RequestSendStageForNotification {
            get {
                return ResourceManager.GetString("RequestSendStageForNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Po zajavke № {0} napravlen zapros. Srok predostavlenija otveta do {1} g. Podrobnee v Lichnom kabinete. № {0} otinim bojynsha suratu zholdandy. Zhauap beru merzimi {1} zh. dejin. Tolygyrak Zheke kabinette..
        /// </summary>
        internal static string RequestStatementExamination {
            get {
                return ResourceManager.GetString("RequestStatementExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Po zajavke № {0} napravlen zapros. Podrobnee v Lichnom kabinete. № {0} otinim bojynsha suratu zholdandy..
        /// </summary>
        internal static string RequestStatementFullExamination {
            get {
                return ResourceManager.GetString("RequestStatementFullExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Po zajavke № {0} srok podachi vozrazhenija do {1}. Podrobnee v Lichnom kabinete. № {0} otinim bojynsha karsylyk beru merzimi {1} zh. dejin. Tolygyrak Zheke kabinette..
        /// </summary>
        internal static string SendStageForDecision {
            get {
                return ResourceManager.GetString("SendStageForDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Po zajavke № {0} napravlen zapros. Srok predostavlenija otveta do {1} g. Podrobnee v Lichnom kabinete. № {0} otinim bojynsha suratu zholdandy. Zhauap beru merzimi {1} zh. dejin. Tolygyrak Zheke kabinette..
        /// </summary>
        internal static string SendStageForRequest {
            get {
                return ResourceManager.GetString("SendStageForRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zajavleniju na registraciju dogovora prisvoen  № {0}.  Podrobnee v Lichnom kabinete. Shartty tirkeu otinishine № {0} tagajyndaldy. Tolygyrak Zheke kabinette..
        /// </summary>
        internal static string SendStageForStatement {
            get {
                return ResourceManager.GetString("SendStageForStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srok oplaty za podachu zajavlenija № {0} dо {1}. Podrobnee v Lichnom kabinete. № {0} otinishti beru үshin toleu merzimi {1} zh. dejin. Tolygyrak Zheke kabinette..
        /// </summary>
        internal static string WaitingForPaymentFiling {
            get {
                return ResourceManager.GetString("WaitingForPaymentFiling", resourceCulture);
            }
        }
    }
}
