update DicRouteStages set ContractStatusId = (select id from DicContractStatuses where code = 'D.TZ') where code = 'DK_GR01.1'
update DicRouteStages set ContractStatusId = (select id from DicContractStatuses where code = 'W') where code = 'DK01.1'
update DicRouteStages set ContractStatusId = (select id from DicContractStatuses where code = 'W') where code = 'DK01.2'
update DicRouteStages set ContractStatusId = (select id from DicContractStatuses where code = 'W') where code = 'DK01.3'
update DicRouteStages set ContractStatusId = (select id from DicContractStatuses where code = 'W') where code = 'DK01.4'
update DicRouteStages set ContractStatusId = (select id from DicContractStatuses where code = 'W') where code = 'DK02.1'
update DicRouteStages set ContractStatusId = (select id from DicContractStatuses where code = 'W') where code = 'DK02.1.0'
update DicRouteStages set ContractStatusId = (select id from DicContractStatuses where code = 'W') where code = 'DK02.2'
update DicRouteStages set ContractStatusId = (select id from DicContractStatuses where code = 'W') where code = 'DK02.2.0'
update DicRouteStages set ContractStatusId = (select id from DicContractStatuses where code = '03.15') where code = 'DK02.2.1'
update DicRouteStages set ContractStatusId = (select id from DicContractStatuses where code = 'W') where code = 'DK02.4'
update DicRouteStages set ContractStatusId = (select id from DicContractStatuses where code = 'W') where code = 'DK02.4.0'
update DicRouteStages set ContractStatusId = (select id from DicContractStatuses where code = 'W') where code = 'DK02.4.1'
update DicRouteStages set ContractStatusId = (select id from DicContractStatuses where code = 'W') where code = 'DK02.4.3' and nameru = 'Продление ответа на запрос'
update DicRouteStages set ContractStatusId = (select id from DicContractStatuses where code = 'W') where code = 'DK02.4.2' and nameru = 'Ожидается ответ на запрос'
update DicRouteStages set ContractStatusId = (select id from DicContractStatuses where code = 'W') where code = 'DK02.5.1'
update DicRouteStages set ContractStatusId = (select id from DicContractStatuses where code = 'W') where code = 'DK02.5.3'
update DicRouteStages set ContractStatusId = (select id from DicContractStatuses where code = 'W') where code = 'DK02.5.4'
update DicRouteStages set ContractStatusId = (select id from DicContractStatuses where code = 'W') where code = 'DK02.6'
update DicRouteStages set ContractStatusId = (select id from DicContractStatuses where code = 'W') where code = 'DK02.7'
update DicRouteStages set ContractStatusId = (select id from DicContractStatuses where code = '03.33') where code = 'DK02.7.1'
update DicRouteStages set ContractStatusId = (select id from DicContractStatuses where code = '03.15') where code = 'DK02.7.2'
update DicRouteStages set ContractStatusId = (select id from DicContractStatuses where code = 'W') where code = 'DK02.8'
update DicRouteStages set ContractStatusId = (select id from DicContractStatuses where code = 'D.TZ') where code = 'DK02.9.1'
update DicRouteStages set ContractStatusId = (select id from DicContractStatuses where code = '03.20') where code = 'DK02.9.2' and nameru = 'Отказано в регистрации'
update DicRouteStages set ContractStatusId = (select id from DicContractStatuses where code = 'W') where code = 'DK02.9.2' and nameru = 'Уведомление заявителя о решении'
update DicRouteStages set ContractStatusId = (select id from DicContractStatuses where code = '03.9') where code = 'DK03.00'
update DicRouteStages set ContractStatusId = (select id from DicContractStatuses where code = 'D.TZ') where code = 'DK03.03'